### ISSUE TITLE
Remove println in `client_request.rs`

### ISSUE THREAD

**Issue by djmitche** [Gelbpunkt/tokio-websockets#1]
I see `Sending 28` on every client request to my test app. It appears to be coming from a `println!` in this file. Could that be removed, just to keep output clean? Thanks!

**Comment by Gelbpunkt** [comment]
Sorry for that! Seems to be an accidental leftover. Removed it and released 0.3.1 that includes the removal.

**Comment by Gelbpunkt** [comment]
I see you had an issue with `std::error::Error` not being implemented for the error types. I've gone ahead and implemented that in 0.3.2 as well.

**Comment by djmitche** [comment]
Thanks! And thanks again! I apologize for not sending a PR for either of those - I was in a bit of a rush :)
