### ISSUE TITLE
"invalid opcode" error

### ISSUE THREAD

**Issue by Diggsey** [Gelbpunkt/tokio-websockets#29]
I tried to use this crate to connect to Slack's Socket API. The "hello" message is received successfully, but the next message to be received causes an `invalid opcode` error to be returned.

I suspect this library may not be handling continuations correctly?

**Comment by Gelbpunkt** [comment]
Hi there, the library should handle continuations correctly. Could you provide me with a minimal reproducible example so I can look into this? I've never used the slack socket API so that would save me some work digging into it.

**Comment by Diggsey** [comment]
You would need access to a Slack workspace. If you can get access then you can go here: https://api.slack.com/apps/ create an app and enable "Socket mode".

You can then `curl https://slack.com/api/apps.connections.open` using your App's Auth token, which returns a WebSocket URL to connect to.

You'll then need a way to trigger an event on that WebSocket, which you can do by enabling `message.im` under "Subscriptions and Event" and then send a DM to your App from within Slack.

**Comment by Diggsey** [comment]
If you know a good tool for tracing then I can trace the connection for you.

**Comment by Gelbpunkt** [comment]
Seems like there was an oversight in an earlier change for opcode tracking. https://github.com/Gelbpunkt/tokio-websockets/commit/baed1c907469bace51ee99032c4b5c4f200b25ea should fix it, but I'm going to wait for autobahn to pass in CI before making a patch release with this.

**Comment by Diggsey** [comment]
That does appear to fix it, nice! 👍

**Comment by Gelbpunkt** [comment]
Published 0.4.1 with the fix.
