### ISSUE TITLE
cargo.io index error

### ISSUE THREAD

**Issue by n454149301** [Gelbpunkt/tokio-websockets#52]
The version v0.7.0 linked at "https://github.com/rust-lang/crates.io-index/blob/master/to/ki/tokio-websockets" corresponds to a tokio-rustls dependency version of "^0.25". However, the git repository's corresponding tokio-rustls dependency version is "^0.26".

Therefore, when I use "cargo add tokio-websockets", and when I use tokio-rustls, there will be a version inconsistency. But when I use tokio-websockets = {git = "https://github.com/Gelbpunkt/tokio-websockets.git", branch = "main", version = "0.7.0"}, it works normally.

**Comment by Gelbpunkt** [comment]
Hi there, this is not an issue since it is normal for crates.io releases to be a bit behind unreleased changes. That said, version 0.8.0 is now released to crates.io and supports rustls 0.23.
