### ISSUE TITLE
Add support for custom rustls connector without pulling in extra dependencies beyond rustls

### ISSUE THREAD

**Issue by devanlai** [Gelbpunkt/tokio-websockets#65]
I'm trying to configure a custom TLS connector with tokio-websockets to connect using a client certificate and with a custom root CA store.

Right now, it's kind of inconvenient to do this. The `Connector::Rustls` variant doesn't exist unless I enable one of `rustls-native-roots`, `rustls-webpki-roots`, or `rustls-platform-verifier`. But enabling one of those provider features is undesirable because I don't _want_ those certs in my application, which has its own certificate management policies.

If there was a feature that only signaled that rustls was available for use without implying the presence of one of those pre-defined cert providers, it would make it possible to configure a custom rustls TLS connector without pulling in unwanted dependencies.

**Comment by Gelbpunkt** [comment]
This is something I'd love to support, but I'm unsure about the behavior of e.g. `TlsConnector::new` with such a feature flag enabled. I guess we'd have to return `Plain` there, because making the method unavailable is definitely not an option.

**Comment by devanlai** [comment]
Yeah, I see it would potentially be confusing to enable a feature flag for a tls library but not have tls-capable connectors by default due to not having a trust store. Maybe the feature flag can be named clearly enough to distinguish it. Something like `rustls-bring-your-own-connector`.
