### ISSUE TITLE
FR: Allow access to the underlying stream from WebSocketStream

### ISSUE THREAD

**Issue by devanlai** [Gelbpunkt/tokio-websockets#71]
Currently there's not a convenient way to get a shared reference to the underlying stream from a `WebSocketStream<S>`. I could use `Builder::connect_on()` to connect to an established stream that I've already prepared, but as far as I can tell, there's not a clean way to let `connect()` establish the stream for me and get a reference to it.

In my use case, I'd like to be able to inspect the underlying `MaybeTlsStream<T>` that's internally inside `WebSocketStream<S>`. That way I can inspect the peer certificates and other TLS connection properties to verify certain security properties and log them.

`tokio-tungstenite` provides a [`WebSocketStream::get_ref()`](https://docs.rs/tokio-tungstenite/latest/tokio_tungstenite/struct.WebSocketStream.html#method.get_ref) method that provides a shared reference to the underlying stream.

It also provides a `get_mut()` method to get a mutable reference, but that seems a little dangerous.

**Comment by Gelbpunkt** [comment]
I wanted to add `get_mut()` anyways seeing how more advanced usecases like setting socket options post-connect is enabled by it. It will definitely need a note that writing and reading from the I/O should never be done.

**Comment by devanlai** [comment]
I hadn't thought about setting the socket options, but that makes sense and would be helpful for some of my usecases, now that I think about it.
